// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaKwoSFfXhcAVDg7MRDtYaOFDQ1tG9f4g',
    appId: '1:361114914221:web:fa20d3f61ac4a7d9e36524',
    messagingSenderId: '361114914221',
    projectId: 'cognistore-725e9',
    authDomain: 'cognistore-725e9.firebaseapp.com',
    storageBucket: 'cognistore-725e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6lS7uL0n28cBeNk23Cohqm35W6bgu8oM',
    appId: '1:361114914221:android:dcfe9e66dfa56fb4e36524',
    messagingSenderId: '361114914221',
    projectId: 'cognistore-725e9',
    storageBucket: 'cognistore-725e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgA8W5evz4e82tHX7x4qTunhxAMGmlzvY',
    appId: '1:361114914221:ios:6077bc2992e21961e36524',
    messagingSenderId: '361114914221',
    projectId: 'cognistore-725e9',
    storageBucket: 'cognistore-725e9.firebasestorage.app',
    iosBundleId: 'com.example.cognistore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgA8W5evz4e82tHX7x4qTunhxAMGmlzvY',
    appId: '1:361114914221:ios:6077bc2992e21961e36524',
    messagingSenderId: '361114914221',
    projectId: 'cognistore-725e9',
    storageBucket: 'cognistore-725e9.firebasestorage.app',
    iosBundleId: 'com.example.cognistore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaKwoSFfXhcAVDg7MRDtYaOFDQ1tG9f4g',
    appId: '1:361114914221:web:a714c9d956ea1f4be36524',
    messagingSenderId: '361114914221',
    projectId: 'cognistore-725e9',
    authDomain: 'cognistore-725e9.firebaseapp.com',
    storageBucket: 'cognistore-725e9.firebasestorage.app',
  );
}
